<img src="https://raw.githubusercontent.com/andre-marcos-perez/ebac-course-utils/main/media/logo/newebac_logo_black_half.png" alt="ebac-logo">

---

# **Módulo 4 Parte II** | Data Frames: indexação, filtragem e operações
**Exercícios**<br> 
[Luiz Aires](https://github.com/luizaires)

## 1) Vestibular

Considere que a os dados gerados na célula abaixo contêm o número de acertos de 100 alunos em um vestibular para um curso de exatas, divididas pelos respectivos assuntos. Considere que cada assunto possui um número de questões conforme a tabela abaixo:

| assunto | número de questões |
|:---:|:---:|
| Matemática | 24 |
| Português | 18 |
| Geografia | 8 |
| Inglês | 8 |
| História | 8 |
| Física | 12 |
| Química | 12 |

Usando os comandos de operações com DataFrames que você aprendeu na Aula 03, calcule:

1. (operações com escalar) Calcule o percentual de acerto dos alunos por assunto.  
2. (operações entre *DataFrames) Calcule o total de acertos de cada aluno.  
3. Calcule o porcentual geral de cada aluno.  
4. Suponha que a nota de corte para a segunda fase seja 45. Quantos alunos tiveram nota maior que 45?

In [1]:
import pandas as pd
import numpy as np

np.random.seed(42)

df_mat = pd.DataFrame(np.random.randint(24, size=(100, 1)), columns=['Qt_acertos'])

df_por = pd.DataFrame(np.random.randint(18, size=(100, 1)), columns=['Qt_acertos'])

df_geo = pd.DataFrame(np.random.randint(8, size=(100, 1)), columns=['Qt_acertos'])

df_ing = pd.DataFrame(np.random.randint(8, size=(100, 1)), columns=['Qt_acertos'])

df_his = pd.DataFrame(np.random.randint(8, size=(100, 1)), columns=['Qt_acertos'])

df_fis = pd.DataFrame(np.random.randint(12, size=(100, 1)), columns=['Qt_acertos'])

df_qui = pd.DataFrame(np.random.randint(12, size=(100, 1)), columns=['Qt_acertos'])

In [2]:
#Criando um data frame com a distribuição de questões no vestibular por assunto
assuntos = ['Matemática', 'Português', 'Geografia', 'Inglês', 'História', 'Física', 'Química']
n_questoes = [24, 18, 8, 8, 8, 12, 12]
df_vestibular = pd.DataFrame(data = n_questoes, index = assuntos, columns = ['número de questões'])
df_vestibular

            número de questões
Matemática                  24
Português                   18
Geografia                    8
Inglês                       8
História                     8
Física                      12
Química                     12

In [3]:
#Colocando o número de acertos por assunto para os 100 alunos em único data frame
df_lista = [df_mat, df_por, df_geo, df_ing, df_his, df_fis, df_qui]
df_notas= pd.concat(df_lista, axis = 1, ignore_index = True)
df_notas.columns = assuntos #Renomeando as colunas, usando a lista assunto
df_notas

    Matemática  Português  Geografia  Inglês  História  Física  Química
0            6          7          7       3         1       8        3
1           19         10          0       0         0      11        8
2           14         16          0       5         7       4        4
3           10          7          3       4         0       0        8
4            7          2          2       7         0       9        3
..         ...        ...        ...     ...       ...     ...      ...
95           6          4          7       1         4       9        3
96           8          1          4       6         1       4        3
97          23          5          0       2         4       1        5
98           0         10          3       1         5      10       11
99          11         15          0       1         6       7        2

[100 rows x 7 columns]

---

In [4]:
#Parte 1 - Definindo um data frame contendo o percentual de acertos dos alunos por assunto
df_percentual_acertos = df_notas/n_questoes
df_percentual_acertos

    Matemática  Português  Geografia  Inglês  História    Física   Química
0     0.250000   0.388889      0.875   0.375     0.125  0.666667  0.250000
1     0.791667   0.555556      0.000   0.000     0.000  0.916667  0.666667
2     0.583333   0.888889      0.000   0.625     0.875  0.333333  0.333333
3     0.416667   0.388889      0.375   0.500     0.000  0.000000  0.666667
4     0.291667   0.111111      0.250   0.875     0.000  0.750000  0.250000
..         ...        ...        ...     ...       ...       ...       ...
95    0.250000   0.222222      0.875   0.125     0.500  0.750000  0.250000
96    0.333333   0.055556      0.500   0.750     0.125  0.333333  0.250000
97    0.958333   0.277778      0.000   0.250     0.500  0.083333  0.416667
98    0.000000   0.555556      0.375   0.125     0.625  0.833333  0.916667
99    0.458333   0.833333      0.000   0.125     0.750  0.583333  0.166667

[100 rows x 7 columns]

---

In [5]:
#Parte 2-Calculando total de acertos de cada aluno
#O método sum(), quando aplicado a um data frame, retorna uma série contendo o somatório dos valores da coluna
#indexada pelo nome da coluna.
#Para calcular o total de acertos para cada aluno, devemos somar os valores de cada linha. Portanto, devemos
#utilizar o método T para retornar a transposta, antes de aplicar o método sum()
total_acertos = df_notas.T.sum()
df_notas['Total acertos'] = total_acertos #Criando nova coluna "Total acertos"
df_notas

,Matemática,Português,Geografia,Inglês,História,Física,Química,Total acertos
0,6,7,7,3,1,8,3,35
1,19,10,0,0,0,11,8,48
2,14,16,0,5,7,4,4,50
3,10,7,3,4,0,0,8,32
4,7,2,2,7,0,9,3,30
...,...,...,...,...,...,...,...,...
95,6,4,7,1,4,9,3,34
96,8,1,4,6,1,4,3,27
97,23,5,0,2,4,1,5,40
98,0,10,3,1,5,10,11,40
99,11,15,0,1,6,7,2,42

---

In [6]:
#Parte 3-Cálculo do percentual de acertos de cada aluno
total_acertos/sum(n_questoes)

0     0.388889
1     0.533333
2     0.555556
3     0.355556
4     0.333333
        ...
95    0.377778
96    0.300000
97    0.444444
98    0.444444
99    0.466667
Length: 100, dtype: float64

---

In [7]:
#Parte 4-Total de alunos que passaram para 2ª fase por obterem mais de 45 acertos
sum(total_acertos > 45)

31

---

## 2) Vestibular II

Ainda sobre o mesmo banco de dados:

1. Neste vestibular, quem 'zera' em matemática, física ou química está desqualificado. Monte um novo *DataFrame* com os alunos desqualificados por este critério.
2. Quantos são esses alunos?
3. Qual a média desses alunos em história e geografia?
4. Monte um *DataFrame* com os alunos que passaram para a segunda fase. Repare que estes alunos não podem ter sido desqualificados.

In [8]:
#Parte 1-Data frame contendo os dados apenas dos alunos desqualificados
i_desqualificados = (df_notas['Matemática'] == 0)|(df_notas['Física'] == 0) |(df_notas['Química'] == 0)
df_desqualificados = df_notas[i_desqualificados]
df_desqualificados

,Matemática,Português,Geografia,Inglês,História,Física,Química,Total acertos
3,10,7,3,4,0,0,8,32
6,6,0,7,7,5,0,4,29
10,10,8,3,2,1,7,0,31
12,20,8,3,7,1,0,3,42
14,7,11,1,7,1,4,0,31
20,23,11,6,5,6,2,0,53
25,0,4,7,4,0,4,8,27
26,11,14,6,2,7,0,0,40
27,21,13,1,5,7,3,0,50
33,14,8,0,5,6,6,0,39
35,11,14,6,3,3,0,11,48
49,8,1,1,0,1,0,8,19
56,7,6,7,5,6,0,8,39
65,1,8,2,4,3,0,6,24
66,5,4,3,6,3,0,10,31
72,11,16,3,4,7,0,9,50
73,1,16,2,4,3,0,11,37
74,9,11,0,7,5,7,0,39
84,15,1,0,5,1,0,4,26
89,23,11,7,7,6,9,0,63
92,14,10,1,6,1,8,0,40
94,0,5,2,6,1,3,8,25
98,0,10,3,1,5,10,11,40

---

In [9]:
#Parte 2-Contando número de alunos desqualificados, usando método count()
#Se aplicado ao data frame, o método count() retorna uma series, contendo o quantidade de valores em cada coluna.
#Por isso, aplicamos um método a uma linha qualquer para obter um único valor
df_desqualificados['Total acertos'].count()

23

---

In [10]:
#Parte 3-Média dos alunos em História
df_desqualificados['História'].mean()

3.4347826086956523

In [11]:
#Parte 3-Média dos alunos em Geografia
df_desqualificados['Geografia'].mean()

3.217391304347826

---

In [12]:
#Parte 4-Data Frame dos alunos que passaram para segunda fase
df_segunda_fase = df_notas[(~i_desqualificados) & (df_notas['Total acertos'] > 45)]
df_segunda_fase

,Matemática,Português,Geografia,Inglês,História,Física,Química,Total acertos
1,19,10,0,0,0,11,8,48
2,14,16,0,5,7,4,4,50
5,20,2,5,3,2,9,9,50
7,18,4,4,7,7,1,8,49
8,22,9,2,7,6,5,7,58
17,21,15,2,2,4,2,6,52
18,20,4,3,5,3,11,4,50
24,20,2,7,5,3,11,2,50
31,15,13,3,1,3,9,10,54
36,22,9,6,6,1,4,8,56
37,19,12,5,7,1,6,2,52
39,4,16,2,4,6,9,8,49
40,18,3,6,3,6,5,6,47
42,20,6,7,7,2,3,3,48
45,17,10,0,2,6,9,4,48
48,17,6,0,7,5,9,11,55
60,16,8,0,4,4,7,9,48
62,17,6,2,4,7,1,9,46
67,21,0,7,2,4,2,10,46
70,21,14,0,3,5,11,8,62
71,17,8,7,6,4,2,9,53
77,15,2,5,7,6,11,7,53
78,14,16,7,2,7,11,9,66
81,22,16,2,0,4,1,10,55
88,20,1,1,5,7,9,7,50
93,12,16,5,5,6,6,6,56

---

## 3) Vacinações no Acre
Vamos trabalhar agora com a base de vacinações no Acre. Para facilitar a sua vida, copiamos o link do arquivo na célula abaixo.

1. Quantas vacinas estão registradas nessa base?  
2. Quantos pacientes foram vacinados? (considere um paciente para cada valor único de ```paciente_id```)  
3. Quantos pacientes únicos tomaram a primeira dose? OBS: Há um caractere especial neste campo. Receba os valores do campo com o método ```.unique()```.   
4. Quantos pacientes com menos de 18 anos foram vacinados?  
5. Quantos estabelecimentos aplicaram vacina no Acre?


**OBS:** O portal do DATASUS pode apresentar instabilidades, retornando um erro na segunda célula abaixo. Por este motivo está disponível uma base estática, que se for baixada para o seu *working directory* pode ser lida com este comando: ```df = pd.read_csv('registros de vacinacao covid ACRE.csv', sep=';')```.

**OBS2:** Para saber qual é o seu working directory, rode no jupyter: ```!pwd```.

In [13]:
df = pd.read_csv('registros de vacinacao covid ACRE.csv', sep=';')
df.head()

,document_id,paciente_id,paciente_idade,paciente_datanascimento,paciente_enumsexobiologico,paciente_racacor_codigo,paciente_racacor_valor,paciente_endereco_coibgemunicipio,paciente_endereco_copais,paciente_endereco_nmmunicipio,...,vacina_lote,vacina_fabricante_nome,vacina_fabricante_referencia,vacina_dataaplicacao,vacina_descricao_dose,vacina_codigo,vacina_nome,sistema_origem,data_importacao_rnds,id_sistema_origem
0,b19cd280-474c-4c22-a35d-8c06bc04a4e0-i0b0,2e091c9a37d3f50d1d705fc80c6448c6fc69b44da9e936...,69,28/12/1951,F,3,PARDA,120050.0,10.0,SENA MADUREIRA,...,210052A,FUNDACAO BUTANTAN,Organization/61189445000156,23/03/2021,1ª Dose,86,Covid-19-Coronavac-Sinovac/Butantan,Novo PNI,2021-03-25T03:27:19.000Z,NaN
1,a1acc0b6-1cf6-4c4b-adcb-06b473a0faaf-i0b0,f4e17a9e5354cb45e223d85eda02fb2f76048c801675f5...,81,22/11/1939,M,3,PARDA,120040.0,10.0,RIO BRANCO,...,210110,FUNDACAO BUTANTAN,Organization/61189445000156,29/04/2021,2ª Dose,86,Covid-19-Coronavac-Sinovac/Butantan,Novo PNI,2021-04-30T16:03:14.000Z,NaN
2,af279a98-ba1f-47ea-8214-314a98040b0d-i0b0,6734b26bccf826130ebffa66575977bbe71477b12bcf42...,69,14/08/1951,M,4,AMARELA,120020.0,10.0,CRUZEIRO DO SUL,...,210135,FUNDACAO BUTANTAN,Organization/61189445000156,16/04/2021,1ª Dose,86,Covid-19-Coronavac-Sinovac/Butantan,Novo PNI,2021-04-16T15:54:39.000Z,NaN
3,4879308e-5050-46bb-b8e2-11fa5646a05c-i0b0,84a341fd350c1ba7117fccbb4d2df417bc0fac0fffac37...,51,15/12/1969,F,3,PARDA,120040.0,10.0,RIO BRANCO,...,202010040,FUNDACAO BUTANTAN,Organization/61189445000156,19/02/2021,2ª Dose,86,Covid-19-Coronavac-Sinovac/Butantan,Novo PNI,2021-03-10T14:40:54.000Z,NaN
4,000e911b-e3a4-4114-a735-d1f2e6e3797f-i0b0,c59571e19f368d4b0cf08cd3bcabb32e5cd8baad5340f6...,65,21/11/1955,M,3,PARDA,120040.0,10.0,RIO BRANCO,...,212VCD001ZVB,FUNDACAO OSWALDO CRUZ,Organization/33781055000135,29/03/2021,1ª Dose,85,Vacina Covid-19 - Covishield,Novo PNI,2021-04-03T19:44:28.000Z,NaN

---

In [14]:
#Parte 1-Número de vacinas registradas
print(df['vacina_nome'].unique())
print(df['vacina_nome'].nunique())

['Covid-19-Coronavac-Sinovac/Butantan' 'Vacina Covid-19 - Covishield'
 'Covid-19-AstraZeneca'
 'Vacina covid-19 - BNT162b2 - BioNTech/Fosun Pharma/Pfizer'
 'Vacina covid-19 - Ad26.COV2.S - Janssen-Cilag']
5

In [15]:
#Parte 2-Número de pacientes vacinados
df['paciente_id'].nunique()

120517

In [16]:
#Parte 3-Número de pacientes "únicos" que tomaram primeira dose
print(df['vacina_descricao_dose'].unique())
#Aplicando método nunique() após filtrar a coluna "paciente_id" com os pacientes que tomaram a primeira dose
print(df.loc[df['vacina_descricao_dose'] == '\xa0\xa0\xa0\xa01ª\xa0Dose', 'paciente_id'].nunique())

['\xa0\xa0\xa0\xa01ª\xa0Dose' '\xa0\xa0\xa0\xa02ª\xa0Dose'
 '\xa0\xa0\xa0\xa0Dose\xa0']
119713

In [17]:
#Parte 3-Número com menos de 18 vacinados
df.loc[df['paciente_idade'] < 18, 'paciente_id'].nunique()

47

In [18]:
#Parte 3-Número de estabelecimentos que aplicaram vacina no Acre
df['estabelecimento_razaosocial'].nunique()

42

---

## 4) Vacinação II
Gere um *DataFrame* que contenha somente os estabelecimentos que aplicaram vcinas a menores de 18 anos. Nesse *DataFrame* devem conter somente os dados dos estabelecimentos, mais uma coluna sendo a quantidade de vacinas que o estabelecimento aplicou a menores de 18 anos.  
  
1. crie uma cópia do *DataFrame* original, contendo somente os registros de vacinas realizadas a menores de 18 anos.  
2. crie uma lista das colunas desse *DataFrame* com o atributo de *DataFrame* **.columns()**  
3. Nesse *DataFrame* faça uma contagem do campo ```vacina_categoria_nome```.
3. a partir da lista de colunas, escolha somente aquelas que são referentes ao estabelecimento, faça uma lista com esses valores.  
4. usando o método *.loc*, selecione somente essas variáveis  
5. Aplique o método **.drop_duplicates** e crie uma lista com uma linha para cada estabelecimento, com os dados do estabelecimento

In [19]:
#Parte 1-Data frame com registre de vacinação apenas de menores de 19 anos
df_menos_18 = df[df['paciente_idade'] < 18].copy()
df_menos_18.head()

,document_id,paciente_id,paciente_idade,paciente_datanascimento,paciente_enumsexobiologico,paciente_racacor_codigo,paciente_racacor_valor,paciente_endereco_coibgemunicipio,paciente_endereco_copais,paciente_endereco_nmmunicipio,...,vacina_lote,vacina_fabricante_nome,vacina_fabricante_referencia,vacina_dataaplicacao,vacina_descricao_dose,vacina_codigo,vacina_nome,sistema_origem,data_importacao_rnds,id_sistema_origem
1567,fdca313f-b348-422d-94d4-f2c66a87868c-i0b0,f5e6b8c44f7c4d13a87c582def5e8d460435b02f26af8c...,17,18/07/2003,F,4,AMARELA,120025.0,10.0,EPITACIOLANDIA,...,213VCD003W,FUNDACAO OSWALDO CRUZ,Organization/33781055000135,12/05/2021,1ª Dose,85,Vacina Covid-19 - Covishield,Novo PNI,2021-05-13T16:16:42.000Z,NaN
6250,b7431955-1faa-4c1e-9246-7c1e7b8bb3cb-i0b0,e1a45c07e3c393d5f0eccf4204a7ceab338f4f06696ecb...,16,18/05/2004,M,3,PARDA,120040.0,10.0,RIO BRANCO,...,200278,FUNDACAO BUTANTAN,Organization/61189445000156,29/01/2021,1ª Dose,86,Covid-19-Coronavac-Sinovac/Butantan,Novo PNI,2021-02-06T14:02:07.000Z,NaN
9569,fdb8d3b6-14d9-4bcc-9cfe-acd46b4a317a-i0b0,7cf3b238383a70eeb26841c01817737c9706d5b231e8c2...,17,23/01/2004,F,99,SEM INFORMACAO,120020.0,10.0,CRUZEIRO DO SUL,...,213VCD042Z,FUNDACAO OSWALDO CRUZ,Organization/33781055000135,15/05/2021,1ª Dose,85,Vacina Covid-19 - Covishield,Novo PNI,2021-05-18T03:17:02.000Z,NaN
11338,647e2301-3ba4-463a-8d1e-2b6f38a4d99e-i0b0,53eb7fed5faa26ad17ce21ee378f28e25399ab7e90bc05...,17,04/05/2003,F,4,AMARELA,120030.0,10.0,FEIJO,...,4120Z004,FUNDACAO OSWALDO CRUZ,Organization/33781055000135,09/02/2021,1ª Dose,85,Vacina Covid-19 - Covishield,Novo PNI,2021-02-09T22:08:13.000Z,NaN
15144,7f469e03-bece-49d0-bebc-33ad98e27f54-i0b0,dbaa6420d8a815158387668d0a59a19cf2bb63958e35d1...,16,22/08/2004,F,5,INDIGENA,120035.0,10.0,MARECHAL THAUMATURGO,...,202010028,FUNDACAO BUTANTAN,Organization/61189445000156,28/01/2021,1ª Dose,86,Covid-19-Coronavac-Sinovac/Butantan,Novo PNI,2021-02-09T19:26:03.000Z,NaN

---

In [20]:
#Parte 2-List contendo nomes das colunas do data frame
colunas = list(df_menos_18.columns)
colunas

['document_id',
 'paciente_id',
 'paciente_idade',
 'paciente_datanascimento',
 'paciente_enumsexobiologico',
 'paciente_racacor_codigo',
 'paciente_racacor_valor',
 'paciente_endereco_coibgemunicipio',
 'paciente_endereco_copais',
 'paciente_endereco_nmmunicipio',
 'paciente_endereco_nmpais',
 'paciente_endereco_uf',
 'paciente_endereco_cep',
 'paciente_nacionalidade_enumnacionalidade',
 'estabelecimento_valor',
 'estabelecimento_razaosocial',
 'estalecimento_nofantasia',
 'estabelecimento_municipio_codigo',
 'estabelecimento_municipio_nome',
 'estabelecimento_uf',
 'vacina_grupoatendimento_codigo',
 'vacina_grupoatendimento_nome',
 'vacina_categoria_codigo',
 'vacina_categoria_nome',
 'vacina_lote',
 'vacina_fabricante_nome',
 'vacina_fabricante_referencia',
 'vacina_dataaplicacao',
 'vacina_descricao_dose',
 'vacina_codigo',
 'vacina_nome',
 'sistema_origem',
 'data_importacao_rnds',
 'id_sistema_origem']

---

In [21]:
#Parte 3-Contagem do campo "vacina_categoria_nome"
df_menos_18['vacina_categoria_nome'].value_counts()

Povos Indígenas                     33
Trabalhadores de Saúde               9
Povos e Comunidades Tradicionais     9
Comorbidades                         2
Faixa Etária                         1
Name: vacina_categoria_nome, dtype: int64

---

In [22]:
#Parte 4 e 5-Data frame com apenas informações referentes ao establecimento que aplicaram vacinas a menores de 18 anos
df_estabelecimento_menos_18 = df_menos_18.loc[:, 'estabelecimento_valor':'estabelecimento_uf']
df_estabelecimento_menos_18

,estabelecimento_valor,estabelecimento_razaosocial,estalecimento_nofantasia,estabelecimento_municipio_codigo,estabelecimento_municipio_nome,estabelecimento_uf
1567,2001314,PREFEITURA MUNICIPAL DE EPITACIOLANDIA,ESF JOAO ALVES DA SILVA,120025,EPITACIOLANDIA,AC
6250,6917291,PREFEITURA MUNICIPAL DE RIO BRANCO,DEPARTAMENTO DE VIGILANCIA EPIDEMIOLOGICA E AM...,120040,RIO BRANCO,AC
9569,6159087,PREFEITURA MUNICIPAL DE CRUZEIRO DO SUL,SECRETARIA MUNICIPAL DE SAUDE DE CRUZEIRO DO SUL,120020,CRUZEIRO DO SUL,AC
11338,2000040,PREFEITURA MUNICIPAL DE FEIJO,CENTRO DE SAUDE DIAMANTINO MACEDO,120030,FEIJO,AC
15144,7625855,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,POLO BASE DE MARECHAL THAUMATURGO,120035,MARECHAL THAUMATURGO,AC
17153,6748759,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,POLO BASE DE FEIJO,120030,FEIJO,AC
18361,6308740,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,POLO BASE DE PORTO WALTER,120039,PORTO WALTER,AC
18608,2001748,PREFEITURA MUNICIPAL DE PORTO WALTER,UBS VICENTE VARELA DE ALMEIDA,120039,PORTO WALTER,AC
20204,6917682,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,POLO BASE DE CRUZEIRO DO SUL,120020,CRUZEIRO DO SUL,AC
20759,6917291,PREFEITURA MUNICIPAL DE RIO BRANCO,DEPARTAMENTO DE VIGILANCIA EPIDEMIOLOGICA E AM...,120040,RIO BRANCO,AC
21119,6428940,PREFEITURA MUNICIPAL DE ASSIS BRASIL,POLO BASE DE ASSIS BRASIL,120005,ASSIS BRASIL,AC
27860,7625855,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,POLO BASE DE MARECHAL THAUMATURGO,120035,MARECHAL THAUMATURGO,AC
29127,6612385,PREFEITURA MUNICIPAL DE TARAUACA,UNIDADE ASSISTENCIAL A SAUDE INDIGENA DE TARAU...,120060,TARAUACA,AC
31200,7625855,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,POLO BASE DE MARECHAL THAUMATURGO,120035,MARECHAL THAUMATURGO,AC
35654,6159087,PREFEITURA MUNICIPAL DE CRUZEIRO DO SUL,SECRETARIA MUNICIPAL DE SAUDE DE CRUZEIRO DO SUL,120020,CRUZEIRO DO SUL,AC
38412,6159087,PREFEITURA MUNICIPAL DE CRUZEIRO DO SUL,SECRETARIA MUNICIPAL DE SAUDE DE CRUZEIRO DO SUL,120020,CRUZEIRO DO SUL,AC
51872,2000040,PREFEITURA MUNICIPAL DE FEIJO,CENTRO DE SAUDE DIAMANTINO MACEDO,120030,FEIJO,AC
57405,9648968,DISTRITO SANITARIO ESPECIAL DE SAUDE INDIGENA ...,POLO INDIGENA DE MANOEL URBANO,120034,MANOEL URBANO,AC
61131,6430201,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO JURUA,POLO BASE INDIGENA,120032,JORDAO,AC
62742,6917291,PREFEITURA MUNICIPAL DE RIO BRANCO,DEPARTAMENTO DE VIGILANCIA EPIDEMIOLOGICA E AM...,120040,RIO BRANCO,AC
66922,7625855,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,POLO BASE DE MARECHAL THAUMATURGO,120035,MARECHAL THAUMATURGO,AC
68290,6955525,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,POLO BASE DE MANCIO LIMA,120033,MANCIO LIMA,AC
69882,5336171,SECRETARIA DE ESTADO DE SAUDE DO ACRE,HOSPITAL REGIONAL DO JURUA,120020,CRUZEIRO DO SUL,AC
70881,6697151,MINISTERIO DA SAUDE,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO PURUS,120050,SENA MADUREIRA,AC
75368,6748759,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,POLO BASE DE FEIJO,120030,FEIJO,AC
78289,6430201,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO JURUA,POLO BASE INDIGENA,120032,JORDAO,AC
79146,2001748,PREFEITURA MUNICIPAL DE PORTO WALTER,UBS VICENTE VARELA DE ALMEIDA,120039,PORTO WALTER,AC
81424,6955525,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,POLO BASE DE MANCIO LIMA,120033,MANCIO LIMA,AC
84331,2001748,PREFEITURA MUNICIPAL DE PORTO WALTER,UBS VICENTE VARELA DE ALMEIDA,120039,PORTO WALTER,AC
88619,6430201,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO JURUA,POLO BASE INDIGENA,120032,JORDAO,AC
89601,7625855,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,POLO BASE DE MARECHAL THAUMATURGO,120035,MARECHAL THAUMATURGO,AC
94858,2001748,PREFEITURA MUNICIPAL DE PORTO WALTER,UBS VICENTE VARELA DE ALMEIDA,120039,PORTO WALTER,AC
95916,7625855,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,POLO BASE DE MARECHAL THAUMATURGO,120035,MARECHAL THAUMATURGO,AC
101402,3323307,PREFEITURA MUNICIPAL DE PORTO ACRE,UNIDADE DE SAUDE DA FAMILIA ALVARO ARAUJO NOBRE,120080,PORTO ACRE,AC
104776,2001748,PREFEITURA MUNICIPAL DE PORTO WALTER,UBS VICENTE VARELA DE ALMEIDA,120039,PORTO WALTER,AC
111242,6430201,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO JURUA,POLO BASE INDIGENA,120032,JORDAO,AC
116510,6955525,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,POLO BASE DE MANCIO LIMA,120033,MANCIO LIMA,AC
119906,7625855,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,POLO BASE DE MARECHAL THAUMATURGO,120035,MARECHAL THAUMATURGO,AC
122656,7625855,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,POLO BASE DE MARECHAL THAUMATURGO,120035,MARECHAL THAUMATURGO,AC
123769,6428940,PREFEITURA MUNICIPAL DE ASSIS BRASIL,POLO BASE DE ASSIS BRASIL,120005,ASSIS BRASIL,AC
124696,6308740,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,POLO BASE DE PORTO WALTER,120039,PORTO WALTER,AC
135392,2000040,PREFEITURA MUNICIPAL DE FEIJO,CENTRO DE SAUDE DIAMANTINO MACEDO,120030,FEIJO,AC
136851,6748759,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,POLO BASE DE FEIJO,120030,FEIJO,AC
139074,9648968,DISTRITO SANITARIO ESPECIAL DE SAUDE INDIGENA ...,POLO INDIGENA DE MANOEL URBANO,120034,MANOEL URBANO,AC
140895,7123043,PREFEITURA MUNICIPAL DE JORDAO,SAUDE DA FAMILIA RIBEIRINHA,120032,JORDAO,AC
142027,6428940,PREFEITURA MUNICIPAL DE ASSIS BRASIL,POLO BASE DE ASSIS BRASIL,120005,ASSIS BRASIL,AC
149043,2001748,PREFEITURA MUNICIPAL DE PORTO WALTER,UBS VICENTE VARELA DE ALMEIDA,120039,PORTO WALTER,AC
149795,6748759,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,POLO BASE DE FEIJO,120030,FEIJO,AC
152218,6748759,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,POLO BASE DE FEIJO,120030,FEIJO,AC
153347,6748759,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,POLO BASE DE FEIJO,120030,FEIJO,AC
155238,7625855,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,POLO BASE DE MARECHAL THAUMATURGO,120035,MARECHAL THAUMATURGO,AC
161227,6612385,PREFEITURA MUNICIPAL DE TARAUACA,UNIDADE ASSISTENCIAL A SAUDE INDIGENA DE TARAU...,120060,TARAUACA,AC
163168,6917291,PREFEITURA MUNICIPAL DE RIO BRANCO,DEPARTAMENTO DE VIGILANCIA EPIDEMIOLOGICA E AM...,120040,RIO BRANCO,AC
164046,2001748,PREFEITURA MUNICIPAL DE PORTO WALTER,UBS VICENTE VARELA DE ALMEIDA,120039,PORTO WALTER,AC
164449,2001748,PREFEITURA MUNICIPAL DE PORTO WALTER,UBS VICENTE VARELA DE ALMEIDA,120039,PORTO WALTER,AC

---

In [23]:
#Parte 6-Lista com os dados de cada estabelecimento
list(df_estabelecimento_menos_18.drop_duplicates().values)

[array([2001314, 'PREFEITURA MUNICIPAL DE EPITACIOLANDIA',
        'ESF JOAO ALVES DA SILVA', 120025, 'EPITACIOLANDIA', 'AC'],
       dtype=object),
 array([6917291, 'PREFEITURA MUNICIPAL DE RIO BRANCO',
        'DEPARTAMENTO DE VIGILANCIA EPIDEMIOLOGICA E AMBIENTAL', 120040,
        'RIO BRANCO', 'AC'], dtype=object),
 array([6159087, 'PREFEITURA MUNICIPAL DE CRUZEIRO DO SUL',
        'SECRETARIA MUNICIPAL DE SAUDE DE CRUZEIRO DO SUL', 120020,
        'CRUZEIRO DO SUL', 'AC'], dtype=object),
 array([2000040, 'PREFEITURA MUNICIPAL DE FEIJO',
        'CENTRO DE SAUDE DIAMANTINO MACEDO', 120030, 'FEIJO', 'AC'],
       dtype=object),
 array([7625855, 'DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO JURUA',
        'POLO BASE DE MARECHAL THAUMATURGO', 120035,
        'MARECHAL THAUMATURGO', 'AC'], dtype=object),
 array([6748759, 'DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO JURUA',
        'POLO BASE DE FEIJO', 120030, 'FEIJO', 'AC'], dtype=object),
 array([6308740, 'DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO JURUA',
        'POLO BASE DE PORTO WALTER', 120039, 'PORTO WALTER', 'AC'],
       dtype=object),
 array([2001748, 'PREFEITURA MUNICIPAL DE PORTO WALTER',
        'UBS VICENTE VARELA DE ALMEIDA', 120039, 'PORTO WALTER', 'AC'],
       dtype=object),
 array([6917682, 'DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO JURUA',
        'POLO BASE DE CRUZEIRO DO SUL', 120020, 'CRUZEIRO DO SUL', 'AC'],
       dtype=object),
 array([6428940, 'PREFEITURA MUNICIPAL DE ASSIS BRASIL',
        'POLO BASE DE ASSIS BRASIL', 120005, 'ASSIS BRASIL', 'AC'],
       dtype=object),
 array([6612385, 'PREFEITURA MUNICIPAL DE TARAUACA',
        'UNIDADE ASSISTENCIAL A SAUDE INDIGENA DE TARAUACA POLO BASE',
        120060, 'TARAUACA', 'AC'], dtype=object),
 array([9648968,
        'DISTRITO SANITARIO ESPECIAL DE SAUDE INDIGENA ALTO RIO PURUS',
        'POLO INDIGENA DE MANOEL URBANO', 120034, 'MANOEL URBANO', 'AC'],
       dtype=object),
 array([6430201, 'DISTRITO SANITARIO ESPECIAL INDIGENA ALTO JURUA',
        'POLO BASE INDIGENA', 120032, 'JORDAO', 'AC'], dtype=object),
 array([6955525, 'DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO JURUA',
        'POLO BASE DE MANCIO LIMA', 120033, 'MANCIO LIMA', 'AC'],
       dtype=object),
 array([5336171, 'SECRETARIA DE ESTADO DE SAUDE DO ACRE',
        'HOSPITAL REGIONAL DO JURUA', 120020, 'CRUZEIRO DO SUL', 'AC'],
       dtype=object),
 array([6697151, 'MINISTERIO DA SAUDE',
        'DISTRITO SANITARIO ESPECIAL INDIGENA ALTO PURUS', 120050,
        'SENA MADUREIRA', 'AC'], dtype=object),
 array([3323307, 'PREFEITURA MUNICIPAL DE PORTO ACRE',
        'UNIDADE DE SAUDE DA FAMILIA ALVARO ARAUJO NOBRE', 120080,
        'PORTO ACRE', 'AC'], dtype=object),
 array([7123043, 'PREFEITURA MUNICIPAL DE JORDAO',
        'SAUDE DA FAMILIA RIBEIRINHA', 120032, 'JORDAO', 'AC'],
       dtype=object)]

---